-- ==============================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR FLOOD DELIVERY TRACKING SYSTEM (IDEMPOTENT VERSION)
-- รองรับการกด Run ซ้ำได้ปลอดภัย 100% ไม่ติด Error "already exists"
-- ==============================================================================

-- 1. สร้างตารางหลัก: รายการจัดส่งสินค้า (delivery_orders)
CREATE TABLE IF NOT EXISTS public.delivery_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code BIGINT,
    member_id VARCHAR(50) NOT NULL,
    customer_name TEXT,
    delivery_date TIMESTAMPTZ,
    round VARCHAR(50) DEFAULT 'ปกติ',
    reason TEXT,
    truck_number VARCHAR(50),
    delivery_day VARCHAR(50),
    customer_type VARCHAR(50) DEFAULT 'B2C',
    branch VARCHAR(100) NOT NULL,
    address TEXT,
    gps VARCHAR(100),
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    district VARCHAR(100),
    status VARCHAR(50) DEFAULT 'รอน้ำลด',
    note TEXT DEFAULT '',
    delivery_group VARCHAR(50) DEFAULT 'ยังส่งไม่ได้',
    is_transferred BOOLEAN DEFAULT false,
    transfer_operator VARCHAR(100) DEFAULT '',
    transfer_date VARCHAR(100) DEFAULT '',
    transfer_raw TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- สร้าง Indexes เพื่อความเร็วสูงสุดในการค้นหาและกรองข้อมูล
CREATE INDEX IF NOT EXISTS idx_orders_member_id ON public.delivery_orders (member_id);
CREATE INDEX IF NOT EXISTS idx_orders_branch ON public.delivery_orders (branch);
CREATE INDEX IF NOT EXISTS idx_orders_truck ON public.delivery_orders (truck_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.delivery_orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_group ON public.delivery_orders (delivery_group);
CREATE INDEX IF NOT EXISTS idx_orders_district ON public.delivery_orders (district);

-- 2. สร้างตารางประวัติการติดตามงาน (action_logs)
CREATE TABLE IF NOT EXISTS public.action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    note TEXT,
    user_email VARCHAR(100) DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_action_logs_member_id ON public.action_logs (member_id);

-- 3. สร้างฟังก์ชัน Trigger อัปเดต updated_at อัตโนมัติ
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON public.delivery_orders;
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.delivery_orders
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 4. เปิดใช้งาน Row Level Security (RLS)
ALTER TABLE public.delivery_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_logs ENABLE ROW LEVEL SECURITY;

-- ลบ Policies เดิมก่อน (ถ้ามี) เพื่อไม่ให้เกิด Error: already exists
DROP POLICY IF EXISTS "Allow public read on delivery_orders" ON public.delivery_orders;
DROP POLICY IF EXISTS "Allow public update on delivery_orders" ON public.delivery_orders;
DROP POLICY IF EXISTS "Allow public insert on action_logs" ON public.action_logs;
DROP POLICY IF EXISTS "Allow public read on action_logs" ON public.action_logs;

-- สร้าง Policies ใหม่
CREATE POLICY "Allow public read on delivery_orders" 
    ON public.delivery_orders 
    FOR SELECT 
    USING (true);

CREATE POLICY "Allow public update on delivery_orders" 
    ON public.delivery_orders 
    FOR UPDATE 
    USING (true);

CREATE POLICY "Allow public insert on action_logs" 
    ON public.action_logs 
    FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Allow public read on action_logs" 
    ON public.action_logs 
    FOR SELECT 
    USING (true);

-- 5. เปิด Realtime Replication อย่างปลอดภัย (ตรวจเช็คก่อนเพิ่ม ป้องกัน Error ซ้ำ)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'delivery_orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.delivery_orders;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'action_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.action_logs;
  END IF;
END $$;
