-- ==============================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR COMPLETE DATASET (93,000+ ROWS)
-- โครงสร้างฐานข้อมูลสำหรับเก็บข้อมูลทั้งหมดจาก Google Sheet ครบทุกแผ่นงาน
-- ==============================================================================

-- 1. ตารางฐานข้อมูลสมาชิกและที่อยู่ (members: 39,800+ รายการ)
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id VARCHAR(50) PRIMARY KEY,
    name TEXT,
    address_building TEXT,
    address_subdistrict TEXT,
    full_address TEXT,
    branch VARCHAR(100),
    truck_number VARCHAR(50),
    gps VARCHAR(100),
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    district VARCHAR(100),
    customer_type VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_members_branch ON public.members (branch);
CREATE INDEX IF NOT EXISTS idx_members_truck ON public.members (truck_number);
CREATE INDEX IF NOT EXISTS idx_members_district ON public.members (district);

-- 2. ตารางรายการและรอบการจัดส่งทั้งหมด (deliveries: 53,600+ รายการ)
CREATE TABLE IF NOT EXISTS public.deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(50) NOT NULL,
    customer_name TEXT,
    delivery_date TEXT,
    round VARCHAR(50),
    status_code VARCHAR(50),
    fail_reason TEXT,
    delivery_group VARCHAR(50) DEFAULT 'ปกติ',
    truck_number VARCHAR(50),
    change_bottle VARCHAR(50),
    doc_details TEXT,
    money_collected VARCHAR(50),
    mdfss_note TEXT,
    weekly_round VARCHAR(50),
    customer_type VARCHAR(50),
    branch VARCHAR(100),
    tracking_status VARCHAR(50) DEFAULT 'รอน้ำลด',
    tracking_note TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_deliveries_member_id ON public.deliveries (member_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_branch ON public.deliveries (branch);
CREATE INDEX IF NOT EXISTS idx_deliveries_truck ON public.deliveries (truck_number);
CREATE INDEX IF NOT EXISTS idx_deliveries_fail_reason ON public.deliveries (fail_reason);
CREATE INDEX IF NOT EXISTS idx_deliveries_group ON public.deliveries (delivery_group);
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON public.deliveries (tracking_status);

-- 3. ตารางประวัติการติดตามงาน (action_logs)
CREATE TABLE IF NOT EXISTS public.action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    note TEXT,
    user_email VARCHAR(100) DEFAULT 'Admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_action_logs_member_id ON public.action_logs (member_id);

-- 4. VIEW สำหรับเชื่อมโยงพิกัด GPS อัตโนมัติ (สำหรับแดชบอร์ดและแผนที่)
CREATE OR REPLACE VIEW public.view_flood_delivery_orders AS
SELECT 
    d.id AS id,
    d.member_id,
    COALESCE(d.customer_name, m.name) AS customer_name,
    d.delivery_date,
    d.round,
    d.fail_reason,
    COALESCE(d.truck_number, m.truck_number) AS truck_number,
    COALESCE(d.branch, m.branch) AS branch,
    m.full_address AS address,
    m.gps,
    m.latitude,
    m.longitude,
    m.district,
    d.delivery_group,
    d.tracking_status AS status,
    d.tracking_note AS note,
    d.customer_type
FROM public.deliveries d
LEFT JOIN public.members m ON d.member_id = m.member_id;

-- 5. Row Level Security & Policies
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on members" ON public.members;
CREATE POLICY "Allow public read on members" ON public.members FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on deliveries" ON public.deliveries;
CREATE POLICY "Allow public read on deliveries" ON public.deliveries FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public update on deliveries" ON public.deliveries;
CREATE POLICY "Allow public update on deliveries" ON public.deliveries FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public insert on action_logs" ON public.action_logs;
CREATE POLICY "Allow public insert on action_logs" ON public.action_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read on action_logs" ON public.action_logs FOR SELECT USING (true);

-- 6. Supabase Realtime
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'deliveries'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.deliveries;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = 'action_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.action_logs;
  END IF;
END $$;
